### ISSUE TITLE
SPI example throws permission denied on '/dev/spidev0.0' under GPIO-admin

### ISSUE THREAD

**Issue by evenwestvang** [romilly/quick2wire-python-api#11]
GPIO-admin seems to have installed fine and I can for example run "gpio-admin export 17 pullup" without causing any errors. I'll just run it under root as a workaround. I haven't tried looking at it in the scope yet, but it seems to be working fine.

**Comment by romilly** [comment]
gpio-admin only affects pins used for GPIO, so for I2C and SPI you need to do other things to run non-root.

In the raspbian kernel, the i2c devices come in an i2c group, so you just need to add yourself to that group, but for SPI you need to 
1. create an spi group
2. add yourself to it
3. set up a udev rule to change the spi devices to be part of the group, and 
4. reboot

Alternatively, you can skip steps 3 and 4, but then you'll need to log out and in again to activate the group membership and (as root) manually change the ownership and permissions of the /dev/spidev entries. Those permissions will need to be manually changed whenever you reboot, which is why the udev rule is a better approach.

I hope that's enough to get you going, and I will flesh this out and add a README as quickly as I can.

**Comment by evenwestvang** [comment]
Excellent, that's ample! I'll give it a go this evening.
